/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTabbedPane;
import javax.swing.Timer;
import util.Auth;
import util.MsgBox;
import util.XImage;

/**
 *
 * @author ToanVu
 */
public class ManSysFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainForm
     */
    public ManSysFrame() {
        initComponents();
        init();
        startDongHo();
    }
    
    void init(){
        setSize(960, 600);
        setLocationRelativeTo(null);
        new ChaoJDialog(this, true).setVisible(true);
        new LoginJDialog(this,true).setVisible(true);
    }
     
    private void startDongHo(){
        new Timer(100, new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent evt){
               Date now = new Date();
               SimpleDateFormat formatter = new SimpleDateFormat("hh:mm:ss a");
               lblDongHo.setText(formatter.format(now));
           }
        }).start();
    }
    
    private void openBangCong(){
        if(Auth.isLogin()){
           new BangCongJDialog(this,true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    } 
    private void openBaoHiem(){
        if(Auth.isLogin()){
           new BaoHiemJDialog(this,true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }
     private void openHopDong(){
        if(Auth.isLogin()&& Auth.isManager()){
           new HopDongJDialog(this,true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền xem trang này");
        }
    }
     private void openKT_KL(){
         if(Auth.isLogin()){
            new KTKLJDialog(this,true).setVisible(true);
         } else {
             MsgBox.alert(this,"Vui lòng đăng nhập");
         }
     }
     private void openTangCa(){
         if(Auth.isLogin()){
             new TangCaJDialog(this,true).setVisible(true);
         } else {
             MsgBox.alert(this, "Vui lòng đăng nhập");
         }
     }
     private void dangXuat(){
         if(Auth.isLogin()){
             new LoginJDialog(this,true).setVisible(true);
         }
     }
     private void doiMatKhau(){
         if(Auth.isLogin()){
             new DoiMatKhauJDialog(this,true).setVisible(true);
         } else {
         MsgBox.alert(this, "Vui lòng đăng nhập");
         }
         
     }
       private void openthongKe(){
           if (Auth.isLogin()) {
               new ThongKeJDialog(this, true).setVisible(true);
           } else {
               MsgBox.alert(this, "Vui lòng đăng nhập");
           }
         
     }
       private void openTaiKhoan(){
           if (Auth.isLogin() && Auth.isManager()) {
                new TaiKhoanJDialog(this,true).setVisible(true);
           } else {
               MsgBox.alert(this, "Bạn không có quyền xem trang này");
           }
       }
       private void openNhanVien(){
           if(Auth.isLogin()){
               new NhanVienJDialog(this,true).setVisible(true);
           } else {
               MsgBox.alert(this, "Vui lòng đăng nhập");
           }
       }
        private void openPB_BP(){
           if(Auth.isLogin()){
               new PB_TDJDialog(this,true).setVisible(true);
           } else {
               MsgBox.alert(this, "Vui lòng đăng nhập");
           }
       }
        private void openUngLuong(){
              if (Auth.isLogin() && Auth.isManager()) {
                new UngLuongJDialog(this,true).setVisible(true);
           } else {
               MsgBox.alert(this, "Bạn không có quyền xem trang này");
           }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNhanVien = new javax.swing.JButton();
        btnBangCong = new javax.swing.JButton();
        btnBaoHiem = new javax.swing.JButton();
        btnKT_KL = new javax.swing.JButton();
        btnPhongBan = new javax.swing.JButton();
        btnTangCa = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnHopDong = new javax.swing.JButton();
        btnUngLuong = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnDangXuat = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        pnlNgay = new javax.swing.JPanel();
        btnParrot = new javax.swing.JButton();
        txtSo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        miniBangCong = new javax.swing.JMenu();
        miniBaoHiem = new javax.swing.JMenu();
        miniUngLuong = new javax.swing.JMenuItem();
        miniTaiKhoan = new javax.swing.JMenuItem();
        mniHopDong = new javax.swing.JMenuItem();
        mniKT_KL = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniLuong = new javax.swing.JMenuItem();
        mniGioLam = new javax.swing.JMenuItem();
        mniPhongBan = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhanVien);

        btnBangCong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBangCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Calendar.png"))); // NOI18N
        btnBangCong.setText("Bảng công");
        btnBangCong.setFocusable(false);
        btnBangCong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBangCong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBangCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangCongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBangCong);

        btnBaoHiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBaoHiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Shield.png"))); // NOI18N
        btnBaoHiem.setText("Bảo hiểm");
        btnBaoHiem.setFocusable(false);
        btnBaoHiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBaoHiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBaoHiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoHiemActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBaoHiem);

        btnKT_KL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKT_KL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
        btnKT_KL.setText("KT_KL");
        btnKT_KL.setFocusable(false);
        btnKT_KL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKT_KL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKT_KL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKT_KLActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKT_KL);

        btnPhongBan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPhongBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Brick house.png"))); // NOI18N
        btnPhongBan.setText("Phòng ban");
        btnPhongBan.setFocusable(false);
        btnPhongBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhongBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongBanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPhongBan);

        btnTangCa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTangCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
        btnTangCa.setText("Tăng ca");
        btnTangCa.setFocusable(false);
        btnTangCa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTangCa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTangCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangCaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTangCa);
        jToolBar1.add(jSeparator4);

        btnHopDong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Properties.png"))); // NOI18N
        btnHopDong.setText("Hợp đồng");
        btnHopDong.setFocusable(false);
        btnHopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopDongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHopDong);

        btnUngLuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUngLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
        btnUngLuong.setText("Ứng lương");
        btnUngLuong.setFocusable(false);
        btnUngLuong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUngLuong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUngLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUngLuongActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUngLuong);

        btnTaiKhoan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users.png"))); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setFocusable(false);
        btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTaiKhoan);
        jToolBar1.add(jSeparator6);

        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log out.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDangXuat);

        btnDoiMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.setFocusable(false);
        btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDoiMatKhau);

        btnThoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThoat);

        pnlNgay.setBackground(new java.awt.Color(255, 255, 255));
        pnlNgay.setPreferredSize(new java.awt.Dimension(278, 30));

        btnParrot.setForeground(new java.awt.Color(51, 51, 51));
        btnParrot.setText("Man");
        btnParrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParrotActionPerformed(evt);
            }
        });

        txtSo.setText("Sys");

        javax.swing.GroupLayout pnlNgayLayout = new javax.swing.GroupLayout(pnlNgay);
        pnlNgay.setLayout(pnlNgayLayout);
        pnlNgayLayout.setHorizontalGroup(
            pnlNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayLayout.createSequentialGroup()
                .addComponent(btnParrot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        pnlNgayLayout.setVerticalGroup(
            pnlNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgayLayout.createSequentialGroup()
                .addGroup(pnlNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParrot)
                    .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoMan.jpg"))); // NOI18N

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alarm.png"))); // NOI18N

        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setDoubleBuffered(true);

        mnuHeThong.setText("Hệ thống");
        mnuHeThong.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator2);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(jSeparator1);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        menuBar.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        miniBangCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Calendar.png"))); // NOI18N
        miniBangCong.setText("Bảng công");
        miniBangCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniBangCongActionPerformed(evt);
            }
        });
        mnuQuanLy.add(miniBangCong);

        miniBaoHiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Shield.png"))); // NOI18N
        miniBaoHiem.setText("Bảo hiểm");
        miniBaoHiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniBaoHiemActionPerformed(evt);
            }
        });
        mnuQuanLy.add(miniBaoHiem);

        miniUngLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
        miniUngLuong.setText("Ứng lương");
        miniUngLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniUngLuongActionPerformed(evt);
            }
        });
        mnuQuanLy.add(miniUngLuong);

        miniTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Users.png"))); // NOI18N
        miniTaiKhoan.setText("Tài Khoản");
        miniTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniTaiKhoanActionPerformed(evt);
            }
        });
        mnuQuanLy.add(miniTaiKhoan);

        mniHopDong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Properties.png"))); // NOI18N
        mniHopDong.setText("Hợp đồng");
        mniHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHopDongActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniHopDong);

        mniKT_KL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKT_KL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
        mniKT_KL.setText("KT - KL");
        mniKT_KL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKT_KLActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKT_KL);

        menuBar.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");
        mnuThongKe.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        mniLuong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
        mniLuong.setText("Lương");
        mniLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLuongActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniLuong);

        mniGioLam.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniGioLam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alarm.png"))); // NOI18N
        mniGioLam.setText("Giờ làm");
        mniGioLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioLamActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniGioLam);

        mniPhongBan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniPhongBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Brick house.png"))); // NOI18N
        mniPhongBan.setText("Phòng ban");
        mniPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPhongBanActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniPhongBan);
        mnuThongKe.add(jSeparator3);

        menuBar.add(mnuThongKe);

        mnuTroGiup.setText("Trợ giúp");
        mnuTroGiup.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongDan.setText("Hướng dẫn sử dụng");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHuongDan);
        mnuTroGiup.add(jSeparator5);

        mniGioiThieu.setText("Giới thiệu sản phẩm");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu);

        menuBar.add(mnuTroGiup);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDongHo)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
                doiMatKhau();
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
                dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
                System.exit(0);
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
            openNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPhongBanActionPerformed

    }//GEN-LAST:event_mniPhongBanActionPerformed

    private void mniHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHopDongActionPerformed
                    openHopDong();
    }//GEN-LAST:event_mniHopDongActionPerformed

    private void mniKT_KLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKT_KLActionPerformed
                    openKT_KL();
    }//GEN-LAST:event_mniKT_KLActionPerformed

    private void mniLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLuongActionPerformed
                    openthongKe();
    }//GEN-LAST:event_mniLuongActionPerformed

    private void mniGioLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioLamActionPerformed
                    openthongKe();
    }//GEN-LAST:event_mniGioLamActionPerformed

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed

    }//GEN-LAST:event_mniHuongDanActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed

    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void btnBangCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangCongActionPerformed
        openBangCong();
    }//GEN-LAST:event_btnBangCongActionPerformed

    private void btnBaoHiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoHiemActionPerformed
        openBaoHiem();
    }//GEN-LAST:event_btnBaoHiemActionPerformed

    private void btnHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopDongActionPerformed
        openHopDong();
    }//GEN-LAST:event_btnHopDongActionPerformed

    private void btnTangCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangCaActionPerformed
      openTangCa();
    }//GEN-LAST:event_btnTangCaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
       doiMatKhau();
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        openTaiKhoan();
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnKT_KLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKT_KLActionPerformed
        openKT_KL();
    }//GEN-LAST:event_btnKT_KLActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
      openNhanVien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongBanActionPerformed
     openPB_BP();
    }//GEN-LAST:event_btnPhongBanActionPerformed

    private void btnUngLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUngLuongActionPerformed
        openUngLuong();
    }//GEN-LAST:event_btnUngLuongActionPerformed

    private void miniUngLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniUngLuongActionPerformed
     openUngLuong();
    }//GEN-LAST:event_miniUngLuongActionPerformed

    private void miniBangCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniBangCongActionPerformed
        openBangCong();
    }//GEN-LAST:event_miniBangCongActionPerformed

    private void miniBaoHiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniBaoHiemActionPerformed
       openBaoHiem();
    }//GEN-LAST:event_miniBaoHiemActionPerformed

    private void miniTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniTaiKhoanActionPerformed
        openTaiKhoan();
    }//GEN-LAST:event_miniTaiKhoanActionPerformed

    private void btnParrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParrotActionPerformed
       openGame();
    }//GEN-LAST:event_btnParrotActionPerformed
    void openparrot(){
        try {
               Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"color a && curl parrot.live\"");
        } catch (Exception e) {
             e.printStackTrace();
        }
    }
    void opentelnet(){
        try {
              Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"telnet telehack.com\"");
        } catch (Exception e) {
            MsgBox.alert(this, "Vui lòng mở telnet cilent");
        }
    }
    void openGame(){
        int number = Integer.parseInt(txtSo.getText());
        switch (number) {
            case 1:
                openparrot();
                break;
            case 2:
                opentelnet();
                break;
            default:
               MsgBox.alert(this, "Không có trong chương trình");
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManSysFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManSysFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManSysFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManSysFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManSysFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBangCong;
    private javax.swing.JButton btnBaoHiem;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHopDong;
    private javax.swing.JButton btnKT_KL;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnParrot;
    private javax.swing.JButton btnPhongBan;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnTangCa;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnUngLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu miniBangCong;
    private javax.swing.JMenu miniBaoHiem;
    private javax.swing.JMenuItem miniTaiKhoan;
    private javax.swing.JMenuItem miniUngLuong;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioLam;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHopDong;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKT_KL;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniLuong;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniPhongBan;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlNgay;
    private javax.swing.JTextField txtSo;
    // End of variables declaration//GEN-END:variables

}

